# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Obroom.OBCommander
PackageVersion: 0.1.1
MinimumOSVersion: 10.0.0.0
InstallerType: portable
Commands:
- obcmd
ReleaseDate: 2026-10-01
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/obroom/obcommander/releases/download/win-v0.1.1/obcmd-win-x64-0.1.1.exe
  InstallerSha256: E8698FAABF3662D0711E6882B9649ACDE5FE0E05988A3A5C34900355192570C5
ManifestType: installer
ManifestVersion: 1.12.0
